### ISSUE TITLE
Feasibility Check for Rust

### ISSUE THREAD

**Issue by shpr8875** [cu-ecen-aeld/final-project-Induja21#12]
DoD
As part of this task, feasibility of

Adding meta-rust layer in yocto to be checked
Analaysis on the integration to be captured.
Feasibility of running a userspace application with RUST to be checked
Blockers: SInce it is a Feasibility check task, and meta-rust layer as per official website is not stable , the blockers are unknown which is the purpose to have the feasibility task

**Comment by Induja21** [comment]
As part of this task, few rust programs were written.

- Hello world
- MQTT subscriber program using paho_mqtt crate
- A basic serializer and deserializer program using serde crate

https://github.com/cu-ecen-aeld/final-project-shpr8875/tree/main/rust-examples
Also created corresponding recipe files using "cargo bitbake" command and added as part of the rust recipe in meta custom layer

https://github.com/cu-ecen-aeld/final-project-Induja21/tree/main/meta-custom/recipes-rust

Rust hello world example do not require any addiitional crates and got built and executed successfully on the target. Below is the raspberrypi output for Hellow world

![Image](https://github.com/user-attachments/assets/84414c93-a635-49fd-b93e-ae7e51f64111)

**Comment by Induja21** [comment]
Steps done for rust setup in Kirkstone
1) Added meta-rust layer as git submodule 
2) Included in bblayers.conf file. 
3) Only  default "Helloworld" program was buildable.
Tried to update the crates by inheriting cargo-update-recipe-crates in the recipe file, yet the updation of crates was a failure

Later switched to scarthgap branch of yocto to use the latest rust devtools.
1) Added openembedded /oecore as part of bblayers.conf file
2) Helloworld was buildable
3) When tried to build the custom ser-des-example or mqtt-subscriber or another simple rust program (using chrono) which includes additional crates the build was failing as shown below that unable to locate crates
(Recipes : https://github.com/cu-ecen-aeld/final-project-Induja21/tree/main/meta-custom/recipes-rust
Code: https://github.com/cu-ecen-aeld/final-project-shpr8875/tree/main/rust-examples )
![2024-12-06_11h02_20](https://github.com/user-attachments/assets/ac9321dc-b616-4d2e-bc27-5db6e8b099a6)

4) Tried to update the crates using command "bitbake -c update_crates <recipe-name>" as mentioned in one of the blog posts (https://advt3.com/posts/yocto-rust/) but the problem was that the update_crates depends on a library tomlib which is part of python3.11 , however kirkstone and scathgap uses python3.10, and below was the error seen

![image](https://github.com/user-attachments/assets/1e7ec22f-fcd5-4384-a442-ef8717b3ed09)


5) Tried to update the python3.11 but the regular core-image-aesd build was failing because of this update and hence had to revert back to python3.10

6) To conclude, if we could fix the python3.11 dependency possibly we should be able to update crates and thereby build the rust recipes which includes additiional crates.

Hence decided to stay with python for MQTT and sensor read becuase of incompatibility and build issues with python3.11
