### ISSUE TITLE
Fixed issue with WLAN Configuration.

### ISSUE THREAD

**Issue by shpr8875** [cu-ecen-aeld/final-project-Induja21#13]
As part of this task,
Issues faced due to wlan0 configuration to be fixed in yocto
DoD:
With new yocto image the wifi communication to be established successfully

Blockers: None

**Comment by Induja21** [comment]
As part of this task, issues were observed when trying to load the wlan kernel module. The brcm firmware will be loaded during the bootup. However the wlan chip was not up and the reason was the firmware was not loaded properly. Below was the error shown in the debug logs
![2024-11-19_17h49_27](https://github.com/user-attachments/assets/c49e0ff2-6063-42db-91c3-a9ad396bc8af)
dmesg output:
![2024-11-19_17h49_42](https://github.com/user-attachments/assets/13f83dcb-cd99-4127-84cf-9b9b26d5362a)

**Comment by Induja21** [comment]
I tried to load the driver manually but it failed as the firmware filename got changed from brcm* to bcm*
Also core-image-minimal will not contain these wlan driver by default.
So did below
1) Built core-image-base - with this wlan driver was properly loaded. When given "ifup wlan0" connection was successfully established"
2) Updated the startup manager from sysvinit to systemd . Below is the screenshot of successful connection image

![2024-11-20_10h30_43](https://github.com/user-attachments/assets/ce059b1b-2d64-4bee-b369-4c29f95f790a)

The changes are done as part of 
https://github.com/cu-ecen-aeld/final-project-Induja21/commit/521552ae7382a4475f89cec7064fca8743b7defa
https://github.com/cu-ecen-aeld/final-project-Induja21/commit/76437d12d5375f6bd5dff6cf9e1ef0675831e8e8
